# -*- coding: utf-8 -*-
"""
ds_flips.py -- are the spectrum classes generated by inversion flips?      (Bio 8, follow-up)

THE MOVE.  If a double-stranded reconstruction T contains a k-mer w at one place and its
reverse complement wbar later, the block  w X wbar  may be replaced by its reverse complement
w rc(X) wbar: the endpoints are unchanged, the interior (k+1)-mers move from spec(T) to
spec(Tbar), and T' is again a double-stranded reconstruction.  Both w and wbar are repeated
k-mers of the double cover (w occurs in T and in Tbar), so every flip is a flip between two
visits of a vertex v and of rho(v) on the closed walk of T, and on the walk it reads

      a_0 .. a_{i-1} | a_i .. a_{j-1} | a_j ..   -->   a_0 .. a_{i-1} | rho(a_{j-1}) .. rho(a_i) | a_j ..

The complementary block gives rc(T'), so T -> Tbar is included as the flip of the whole cycle.

THE TEST.  ds_lattice.py's brute force returns every reconstruction as a walk.  We build the
graph whose vertices are the reconstructions (canonical rotation of the content sequence) and
whose edges are single flips, and ask:
  (G1) sequence level: how many components under flips alone; under flips + rc;
  (G2) class level (spectra): is the quotient graph connected from spec(S)?
  (G3) which vertex pairs {v, rho v} are needed: do the cross-strand pairs of S alone suffice,
       or do pairs {a, abar} with a a single-strand repeat become necessary after a flip?
  (G4) flip distance of every class from spec(S).

Run: python -u ds_flips.py           (seconds)
"""

import sys, os, time, collections
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ds_lattice import Cover, load_phix, rc, BRUTE_CAP, row, ROWS


def canon(w):
    """lexicographically least rotation of a tuple"""
    L = len(w)
    ww = w + w
    return min(ww[i:i + L] for i in range(L))


def flips(D, w):
    """all single-flip neighbours of the walk w (tuple of content ids), as canonical tuples,
    together with the vertex pair used; plus the reverse complement of w"""
    L = len(w)
    tail, crho, vrho = D.tail, D.crho, D.vfix
    visits = [tail[a] for a in w]
    out = []
    for i in range(L):
        vi = visits[i]
        target = vrho[vi]
        for t in range(1, L):
            j = (i + t) % L
            if visits[j] != target:
                continue
            rot = w[i:] + w[:i]
            new = tuple(crho[rot[s]] for s in range(t - 1, -1, -1)) + rot[t:]
            out.append((canon(new), frozenset((vi, target))))
    rcw = canon(tuple(crho[a] for a in reversed(w)))
    return out, rcw


def components(nodes, adj):
    comp = {}
    n = 0
    for s in nodes:
        if s in comp:
            continue
        n += 1
        stack = [s]
        comp[s] = n
        while stack:
            x = stack.pop()
            for y in adj[x]:
                if y not in comp:
                    comp[y] = n
                    stack.append(y)
    return comp, n


def main():
    t0 = time.time()
    S = load_phix()
    print("=== are the spectrum classes generated by inversion flips? (phiX174) ===")
    for k in (12, 11):
        D = Cover(S, k)
        walks = []
        buckets, nodes = D.brute(BRUTE_CAP, walks)
        seqs = {}
        for w in walks:
            seqs[canon(w)] = tuple((D.m[a] + 2 * w.count(a) - D.m[a]) // 1 for a in range(D.nA))
        # spectrum of a walk = usage vector
        spec = {}
        for w in seqs:
            c = [0] * D.nA
            for a in w:
                c[a] += 1
            spec[w] = tuple(c)
        n_seq, n_cls = len(seqs), len(set(spec.values()))
        print(f"\n--- k = {k}: {n_seq} reconstructions in {n_cls} spectrum classes ---")
        assert n_seq == int(sum(buckets.values())) and n_cls == len(buckets)

        # S itself as a walk
        arcsS = sorted((a["pos"], D.cid[a["content"]]) for a in D.arcs if a["strand"] == 0)
        wS = canon(tuple(a for _, a in arcsS))
        assert wS in seqs, "S is not among the reconstructions?"
        cS, cSbar = tuple(D.c_strand[0]), tuple(D.c_strand[1])

        # the flip graph
        adj = collections.defaultdict(set)
        adj_rc = collections.defaultdict(set)
        pair_used = collections.defaultdict(set)      # edge -> vertex pairs realising it
        cross = set()
        for w_, fwd, rev in D.cross_strand()[0]:
            cross.add(frozenset((D.vid[w_], D.vid[rc(w_)])))
        for w_, fwd in D.cross_strand()[1]:
            cross.add(frozenset((D.vid[w_],)))
        adj_cross = collections.defaultdict(set)
        n_flips = 0
        for w in seqs:
            nb, rcw = flips(D, w)
            assert rcw in seqs
            adj_rc[w].add(rcw)
            adj_rc[rcw].add(w)
            for v, pair in nb:
                assert v in seqs, "a flip left the reconstruction set"
                n_flips += 1
                if v != w:
                    adj[w].add(v)
                    adj[v].add(w)
                    pair_used[frozenset((w, v))].add(pair)
                    if pair in cross:
                        adj_cross[w].add(v)
                        adj_cross[v].add(w)
        print(f"    {n_flips} flip instances, {sum(len(x) for x in adj.values())//2} distinct flip edges, "
              f"every flip stays inside the reconstruction set")

        # (G1) sequence level
        comp, nc = components(list(seqs), adj)
        adj_both = collections.defaultdict(set)
        for w in seqs:
            adj_both[w] = adj[w] | adj_rc[w]
        comp2, nc2 = components(list(seqs), adj_both)
        sizes = collections.Counter(comp.values())
        print(f"    (G1) sequence graph: {nc} component(s) under flips alone"
              f" (sizes {sorted(sizes.values(), reverse=True)[:8]}{'...' if nc > 8 else ''});"
              f" {nc2} under flips + rc")

        # (G2) class level, from spec(S)
        cadj = collections.defaultdict(set)
        for w in seqs:
            for v in adj[w]:
                if spec[v] != spec[w]:
                    cadj[spec[w]].add(spec[v])
        classes = list(set(spec.values()))
        ccomp, ncc = components(classes, cadj)
        reach = {c for c in classes if ccomp[c] == ccomp[cS]}
        print(f"    (G2) class graph: {ncc} component(s); from spec(S) {len(reach)} of {n_cls} classes are "
              f"reached by flips alone{'' if cSbar in reach else ' (spec(Sbar) NOT among them)'}")
        # same-spectrum flips?
        same = sum(1 for w in seqs for v in adj[w] if spec[v] == spec[w]) // 2
        print(f"         flip edges that stay inside a class: {same}")

        # (G3) restricted to the cross-strand pairs of S
        ccadj = collections.defaultdict(set)
        for w in seqs:
            for v in adj_cross[w]:
                if spec[v] != spec[w]:
                    ccadj[spec[w]].add(spec[v])
        ccomp3, ncc3 = components(classes, ccadj)
        reach3 = {c for c in classes if ccomp3[c] == ccomp3[cS]}
        pairs_all = set()
        for e, ps in pair_used.items():
            pairs_all |= ps
        print(f"    (G3) vertex pairs realising flips: {len(pairs_all)} of which {len(pairs_all & cross)} are "
              f"cross-strand pairs of S ({len(cross)} exist); restricted to those, "
              f"{len(reach3)} of {n_cls} classes are reached from spec(S)")
        extra = [p for p in pairs_all if p not in cross]
        if extra:
            ex = sorted(extra, key=lambda p: min(p))[:4]
            print(f"         examples of the other pairs: " +
                  ", ".join("{" + ", ".join(D.words[v] for v in sorted(p)) + "}" for p in ex))

        # aperiodicity: every reconstruction has trivial rotational symmetry (so the 1/d(T)
        # weights of the lattice sum are all 1)
        aper = all(all(w[i:] + w[:i] != w for i in range(1, len(w))) for w in seqs)
        print(f"    every reconstruction is aperiodic as a cyclic content sequence: {aper}")
        row(f"A{k}", f"k={k}: all {n_seq} reconstructions are aperiodic (all weights 1/d(T) equal 1)",
            f"{n_seq} sequences", "exact", aper)

        # (G5) same-spectrum pairs: joined by flip paths of which minimal length?
        cls_members = collections.defaultdict(list)
        for w in seqs:
            cls_members[spec[w]].append(w)
        within = collections.Counter()
        for c, mem in cls_members.items():
            if len(mem) < 2:
                continue
            for s in mem:
                d = {s: 0}
                fr = [s]
                while fr:
                    nx = []
                    for x in fr:
                        for y in adj[x]:
                            if y not in d:
                                d[y] = d[x] + 1
                                nx.append(y)
                    fr = nx
                for t in mem:
                    if t != s:
                        within[d.get(t, -1)] += 1
        print(f"    (G5) flip distance between reconstructions of the SAME spectrum (ordered pairs): "
              + ", ".join(f"d={d}: {n}" for d, n in sorted(within.items())))

        # (G4) flip distance of every class from spec(S), sequence-level BFS with class recording
        dist = {wS: 0}
        frontier = [wS]
        while frontier:
            nxt = []
            for w in frontier:
                for v in adj[w]:
                    if v not in dist:
                        dist[v] = dist[w] + 1
                        nxt.append(v)
            frontier = nxt
        cdist = {}
        for w, d in dist.items():
            cdist[spec[w]] = min(d, cdist.get(spec[w], 10 ** 9))
        hist = collections.Counter(cdist.values())
        print(f"    (G4) from S: {len(dist)} of {n_seq} sequences reached; class distance histogram "
              + ", ".join(f"d={d}: {n}" for d, n in sorted(hist.items())))
        okG = (len(reach) == n_cls)
        row(f"F{k}", f"k={k}: every spectrum class is reached from spec(S) by inversion flips alone",
            f"{n_cls} classes", "exact", okG)

    print("\n=== battery summary ===")
    bad = [x for x in ROWS if not x[4]]
    print(f"  TOTAL {sum(1 for x in ROWS if x[4])}/{len(ROWS)} passed"
          + ("" if not bad else f"   FAILURES: {[(x[0], x[2]) for x in bad]}"))
    print(f"  elapsed {time.time()-t0:.0f}s")
    return 0 if not bad else 1


if __name__ == "__main__":
    sys.exit(main())
